"""Stable public Quality API with compatibility-preserving lazy imports."""

from __future__ import annotations

from importlib import import_module


_EXPORT_GROUPS = {
    "quality.collector": (
        "QualityCollector",
        "QualityShardPaths",
        "configure_collector",
        "get_collector",
        "reset_collector",
    ),
    "quality.aggregator": (
        "MANIFEST_VERSION",
        "MERGE_VERSION",
        "QualityMergeRequest",
        "QualityMergeResult",
        "merge_quality_run",
    ),
    "quality.classifier": (
        "CLASSIFIER_RULE_VERSION",
        "FINGERPRINT_VERSION",
        "FailureEvidence",
        "classify_failure",
    ),
    "quality.config": (
        "DEFAULT_QUALITY_OUTPUT_DIR",
        "QUALITY_ENABLE_ENV",
        "QUALITY_FLAKY_DB_PATH_ENV",
        "QUALITY_FLAKY_HISTORY_ENABLE_ENV",
        "QUALITY_FLAKY_STATE_ENABLE_ENV",
        "QUALITY_METRICS_ENABLE_ENV",
        "QUALITY_SEMANTIC_ENABLE_ENV",
        "QUALITY_EXECUTION_ID_ENV",
        "QUALITY_OUTPUT_DIR_ENV",
        "QUALITY_RUN_ID_ENV",
        "QualityRuntimeConfig",
        "load_quality_config",
        "parse_quality_enabled",
    ),
    "quality.metrics": (
        "RunMetricsAggregationRequest",
        "RunMetricsAggregationResult",
        "aggregate_run_metrics",
        "count_distribution",
        "metric_bucket_id",
        "numeric_aggregate",
        "ratio_aggregate",
    ),
    "quality.metrics_models": (
        "RUN_METRICS_AGGREGATION_VERSION",
        "RUN_METRICS_MANIFEST_VERSION",
        "RUN_METRICS_SCHEMA_VERSION",
        "MetricCompleteness",
        "NumericAggregate",
        "RatioAggregate",
        "RunMetricsResult",
        "RunMetricsStatus",
    ),
    "quality.flaky_importer": (
        "build_observation_id",
        "check_flaky_database",
        "confirm_flaky_state",
        "evaluate_flaky_state",
        "fold_case_observations",
        "import_flaky_history",
        "list_flaky_governance",
        "mark_flaky_not_flaky",
        "query_flaky_history",
        "query_flaky_states",
        "quarantine_flaky_state",
        "rebuild_flaky_states",
        "reset_flaky_epoch",
        "start_flaky_recovery",
        "cancel_flaky_quarantine",
        "write_flaky_v3_state_report",
    ),
    "quality.flaky_identity": (
        "build_epoch_scope_key",
        "build_flaky_key",
        "normalize_execution_profile",
        "normalize_flaky_environment",
    ),
    "quality.flaky_probe": (
        "CsrfProtector",
        "DispatchResult",
        "DispatchResultKind",
        "FixedJenkinsClient",
        "GitTargetResolver",
        "JenkinsObservation",
        "JenkinsObservationKind",
        "ProbeControlService",
        "ProbeCreateRequest",
        "ProbeEvidenceEnvelope",
        "ProbePlan",
        "ProbeRuntimeConfig",
        "build_probe_envelope",
        "load_probe_controller_runtime_config",
        "load_probe_evidence_key",
        "load_probe_runtime_config",
        "select_probe_nodeid",
        "validate_p0_bundle",
        "verify_probe_envelope",
    ),
    "quality.flaky_models": (
        "FLAKY_ENVIRONMENT_RULE_VERSION",
        "FLAKY_EXECUTION_PROFILE_RULE_VERSION",
        "FLAKY_IDENTITY_RULE_VERSION",
        "FLAKY_IMPORTER_VERSION",
        "FLAKY_IMPORT_SCHEMA_VERSION",
        "FLAKY_OBSERVATION_RULE_VERSION",
        "FLAKY_EVALUATION_SCHEMA_VERSION",
        "FLAKY_PROJECTION_VERSION",
        "FLAKY_STATE_RULE_VERSION",
        "CaseObservation",
        "CaseObservationCandidate",
        "EpochResetRequest",
        "EpochResetResult",
        "FlakyDatabaseCheck",
        "FlakyHistoryEntry",
        "FlakyImportIssue",
        "FlakyImportRequest",
        "FlakyImportResult",
        "FlakyImportStatus",
        "FlakyEvaluationResult",
        "FlakyEvaluationStatus",
        "FlakyGovernanceRecord",
        "FlakyManualActionRequest",
        "FlakyQuarantineRequest",
        "FlakyState",
        "FlakyStateRecord",
        "GovernanceResolution",
        "GovernanceStatus",
        "ObservationOutcome",
    ),
    "quality.identifiers": (
        "NormalizedNodeId",
        "build_case_id",
        "build_execution_id",
        "build_failure_fingerprint",
        "build_failure_message_hash",
        "build_interface_id",
        "build_invocation_id",
        "build_param_hash",
        "build_run_id",
        "build_url_template",
        "new_request_event_id",
        "new_operation_id",
        "new_polling_session_id",
        "new_request_group_id",
        "normalize_failure_message",
        "normalize_nodeid",
    ),
    "quality.junit": (
        "QUALITY_CASE_ID_PROPERTY",
        "QUALITY_INVOCATION_ID_PROPERTY",
        "JUnitCaseEvidence",
        "parse_junit_file",
    ),
    "quality.models": (
        "SCHEMA_VERSION",
        "BusinessStatus",
        "CasePhase",
        "CaseResult",
        "CaseStatus",
        "Confidence",
        "CostSource",
        "FailureCategory",
        "FailureFingerprintSource",
        "FailureRecord",
        "IntegrityIssue",
        "IntegrityStatus",
        "IssueSeverity",
        "OwnerDomain",
        "Protocol",
        "RequestCost",
        "RequestMetric",
        "RequestUsage",
        "RunRecord",
        "RunKind",
        "RunStatus",
    ),
    "quality.redaction": (
        "canonicalize_for_hash",
        "redact_quality_value",
        "sanitize_identifier_part",
        "strip_url_query",
    ),
    "quality.runtime_context": (
        "QualityCaseContext",
        "QualityRunContext",
        "clear_case_context",
        "clear_run_context",
        "get_case_context",
        "get_run_context",
        "reset_case_context",
        "reset_run_context",
        "set_case_context",
        "set_run_context",
    ),
    "quality.storage": (
        "QualityDirectoryLayout",
        "append_jsonl",
        "ensure_quality_dirs",
        "read_jsonl",
        "write_json_atomic",
        "write_jsonl_atomic",
    ),
    "quality.semantic_aggregator": (
        "SemanticMergeRequest",
        "SemanticMergeResult",
        "merge_semantic_run",
    ),
    "quality.semantic_collector": (
        "SemanticCollector",
        "SemanticShardPaths",
        "configure_semantic_collector",
        "get_semantic_collector",
        "reset_semantic_collector",
    ),
    "quality.semantic_models": (
        "SEMANTIC_MANIFEST_VERSION",
        "SEMANTIC_MERGE_VERSION",
        "SEMANTIC_SCHEMA_VERSION",
        "AttemptTransportOutcome",
        "OperationKind",
        "OperationOutcome",
        "OperationRecord",
        "OperationTiming",
        "OperationUsage",
        "PollingOutcome",
        "PollingSessionRecord",
        "RecordCompleteness",
        "RequestGroupRecord",
        "SemanticIntegrityIssue",
        "StreamOutcome",
        "TimingCompleteness",
        "TrafficRole",
        "UsageCompleteness",
    ),
}

_EXPORTS = {
    name: (module_name, name)
    for module_name, names in _EXPORT_GROUPS.items()
    for name in names
}


__all__ = [
    "SCHEMA_VERSION",
    "SEMANTIC_MANIFEST_VERSION",
    "SEMANTIC_MERGE_VERSION",
    "SEMANTIC_SCHEMA_VERSION",
    "AttemptTransportOutcome",
    "BusinessStatus",
    "CasePhase",
    "CaseResult",
    "CaseStatus",
    "CLASSIFIER_RULE_VERSION",
    "Confidence",
    "CostSource",
    "DEFAULT_QUALITY_OUTPUT_DIR",
    "FailureCategory",
    "FailureEvidence",
    "FailureFingerprintSource",
    "FailureRecord",
    "FINGERPRINT_VERSION",
    "FLAKY_ENVIRONMENT_RULE_VERSION",
    "FLAKY_EXECUTION_PROFILE_RULE_VERSION",
    "FLAKY_IDENTITY_RULE_VERSION",
    "FLAKY_IMPORTER_VERSION",
    "FLAKY_IMPORT_SCHEMA_VERSION",
    "FLAKY_OBSERVATION_RULE_VERSION",
    "FLAKY_EVALUATION_SCHEMA_VERSION",
    "FLAKY_PROJECTION_VERSION",
    "FLAKY_STATE_RULE_VERSION",
    "FlakyDatabaseCheck",
    "FlakyHistoryEntry",
    "FlakyImportIssue",
    "FlakyImportRequest",
    "FlakyImportResult",
    "FlakyImportStatus",
    "FlakyEvaluationResult",
    "FlakyEvaluationStatus",
    "FlakyGovernanceRecord",
    "FlakyManualActionRequest",
    "FlakyQuarantineRequest",
    "FixedJenkinsClient",
    "GitTargetResolver",
    "FlakyState",
    "FlakyStateRecord",
    "GovernanceResolution",
    "GovernanceStatus",
    "CsrfProtector",
    "DispatchResult",
    "DispatchResultKind",
    "JenkinsObservation",
    "JenkinsObservationKind",
    "IntegrityIssue",
    "IntegrityStatus",
    "IssueSeverity",
    "JUnitCaseEvidence",
    "MANIFEST_VERSION",
    "MERGE_VERSION",
    "NormalizedNodeId",
    "OwnerDomain",
    "OperationKind",
    "OperationOutcome",
    "OperationRecord",
    "OperationTiming",
    "OperationUsage",
    "ObservationOutcome",
    "PollingOutcome",
    "PollingSessionRecord",
    "Protocol",
    "QUALITY_CASE_ID_PROPERTY",
    "QUALITY_ENABLE_ENV",
    "QUALITY_FLAKY_DB_PATH_ENV",
    "QUALITY_FLAKY_HISTORY_ENABLE_ENV",
    "QUALITY_FLAKY_STATE_ENABLE_ENV",
    "QUALITY_METRICS_ENABLE_ENV",
    "QUALITY_SEMANTIC_ENABLE_ENV",
    "QUALITY_EXECUTION_ID_ENV",
    "QUALITY_INVOCATION_ID_PROPERTY",
    "QUALITY_OUTPUT_DIR_ENV",
    "QUALITY_RUN_ID_ENV",
    "QualityCaseContext",
    "CaseObservation",
    "CaseObservationCandidate",
    "QualityCollector",
    "QualityDirectoryLayout",
    "QualityMergeRequest",
    "QualityMergeResult",
    "QualityRuntimeConfig",
    "RUN_METRICS_AGGREGATION_VERSION",
    "RUN_METRICS_MANIFEST_VERSION",
    "RUN_METRICS_SCHEMA_VERSION",
    "MetricCompleteness",
    "NumericAggregate",
    "RatioAggregate",
    "RunMetricsAggregationRequest",
    "RunMetricsAggregationResult",
    "RunMetricsResult",
    "RunMetricsStatus",
    "QualityRunContext",
    "ProbeControlService",
    "ProbeCreateRequest",
    "ProbeEvidenceEnvelope",
    "ProbePlan",
    "ProbeRuntimeConfig",
    "QualityShardPaths",
    "EpochResetRequest",
    "EpochResetResult",
    "RecordCompleteness",
    "RequestCost",
    "RequestMetric",
    "RequestGroupRecord",
    "RequestUsage",
    "RunRecord",
    "RunKind",
    "RunStatus",
    "SemanticCollector",
    "SemanticIntegrityIssue",
    "SemanticMergeRequest",
    "SemanticMergeResult",
    "SemanticShardPaths",
    "StreamOutcome",
    "TimingCompleteness",
    "TrafficRole",
    "UsageCompleteness",
    "append_jsonl",
    "aggregate_run_metrics",
    "build_case_id",
    "build_epoch_scope_key",
    "build_execution_id",
    "build_failure_fingerprint",
    "build_failure_message_hash",
    "build_flaky_key",
    "build_interface_id",
    "build_invocation_id",
    "build_observation_id",
    "build_param_hash",
    "build_run_id",
    "build_probe_envelope",
    "build_url_template",
    "canonicalize_for_hash",
    "count_distribution",
    "classify_failure",
    "check_flaky_database",
    "confirm_flaky_state",
    "clear_case_context",
    "clear_run_context",
    "configure_collector",
    "configure_semantic_collector",
    "ensure_quality_dirs",
    "evaluate_flaky_state",
    "fold_case_observations",
    "get_case_context",
    "get_collector",
    "get_run_context",
    "get_semantic_collector",
    "import_flaky_history",
    "list_flaky_governance",
    "load_quality_config",
    "load_probe_controller_runtime_config",
    "load_probe_evidence_key",
    "load_probe_runtime_config",
    "merge_quality_run",
    "merge_semantic_run",
    "mark_flaky_not_flaky",
    "metric_bucket_id",
    "new_operation_id",
    "new_polling_session_id",
    "new_request_group_id",
    "new_request_event_id",
    "normalize_execution_profile",
    "normalize_flaky_environment",
    "normalize_failure_message",
    "normalize_nodeid",
    "numeric_aggregate",
    "parse_junit_file",
    "parse_quality_enabled",
    "query_flaky_history",
    "query_flaky_states",
    "ratio_aggregate",
    "quarantine_flaky_state",
    "rebuild_flaky_states",
    "read_jsonl",
    "redact_quality_value",
    "reset_case_context",
    "reset_collector",
    "reset_run_context",
    "reset_semantic_collector",
    "reset_flaky_epoch",
    "start_flaky_recovery",
    "cancel_flaky_quarantine",
    "sanitize_identifier_part",
    "set_case_context",
    "set_run_context",
    "select_probe_nodeid",
    "strip_url_query",
    "validate_p0_bundle",
    "verify_probe_envelope",
    "write_json_atomic",
    "write_jsonl_atomic",
    "write_flaky_v3_state_report",
]


def __getattr__(name: str):
    try:
        module_name, attribute_name = _EXPORTS[name]
    except KeyError as error:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from error
    value = getattr(import_module(module_name), attribute_name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
